compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

defaultSemverRangePrefix: '^'

packageExtensions:
  # see: https://github.com/patternfly/patternfly-react/issues/11923
  '@patternfly/react-code-editor@*':
    peerDependencies:
      'monaco-editor': '^0.52.0'

  # the below can are added after `yarn explain peer-requirements | grep -v ✓`
  # fixing eslint-plugin-testing-library > @typescript-eslint/utils peer dependency contract
  'eslint-plugin-testing-library@*':
    peerDependencies:
      'typescript': '^5.8.3'
  # fixing @commitlint/load > cosmiconfig-typescript-loader peer dependency contract
  '@commitlint/load@*':
    peerDependencies:
      '@types/node': '^24.0.14'
      'typescript': '^5.8.3'
  # fixing cz-conventional-changelog > @commitlint/load peer dependency contract
  'cz-conventional-changelog@*':
    peerDependencies:
      'typescript': '^5.8.3'
      '@types/node': '^24.0.14'
  # fixing commitizen > cz-conventional-changelog peer dependency contract
  'commitizen@*':
    peerDependencies:
      '@types/node': '^24.0.14'
      'typescript': '^5.8.3'

  # this one is strange:
  #  - there's peer dependency to webpack, but I don't think it's necessary
  #  - suggested @module-federation/runtime doesn't refer to variables like __webpack_require__, so it doesn't look
  #    like direct replacement of @module-federation/utilities
  '@module-federation/utilities@*':
    peerDependenciesMeta:
      'webpack':
        'optional': true

yarnPath: .yarn/releases/yarn-4.9.2.cjs
