compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

defaultSemverRangePrefix: "^"

packageExtensions:
  # see: https://github.com/patternfly/patternfly-react/issues/11923
  "@patternfly/react-code-editor@*":
    peerDependencies:
      "monaco-editor": "^0.52.0"
  # this one is strange:
  #  - there's peer dependency to webpack, but I don't think it's necessary
  #  - suggested @module-federation/runtime doesn't refer to variables like __webpack_require__, so it doesn't look
  #    like direct replacement of @module-federation/utilities
  "@module-federation/utilities@*":
    peerDependenciesMeta:
      "webpack":
        "optional": true

yarnPath: .yarn/releases/yarn-4.9.2.cjs
