compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

defaultSemverRangePrefix: "^"

packageExtensions:
  # see: https://github.com/patternfly/patternfly-react/issues/11923
  "@patternfly/react-code-editor@*":
    peerDependencies:
      "monaco-editor": "^0.52.0"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
