compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@commitlint/load@*":
    peerDependencies:
      "@types/node": ^24.0.14
      typescript: ^5.8.3
  "@module-federation/utilities@*":
    peerDependenciesMeta:
      webpack:
        optional: true
  "@patternfly/react-code-editor@*":
    peerDependencies:
      monaco-editor: ^0.52.0
  commitizen@*:
    peerDependencies:
      "@types/node": ^24.0.14
      typescript: ^5.8.3
  cz-conventional-changelog@*:
    peerDependencies:
      "@types/node": ^24.0.14
      typescript: ^5.8.3
  eslint-plugin-testing-library@*:
    peerDependencies:
      typescript: ^5.8.3

yarnPath: .yarn/releases/yarn-4.10.3.cjs
