// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/aggregate24.svg'

const AggregateIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="AggregateIcon"
    />
  )
}

export { AggregateIcon }
