// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/breakpoint.svg'

const BreakpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="BreakpointIcon"
    />
  )
}

export { BreakpointIcon }
