// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/camel-tracing.svg'

const CamelTracingIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CamelTracingIcon"
    />
  )
}

export { CamelTracingIcon }
