// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/camel-route-folder.svg'

const CamelRouteFolderIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CamelRouteFolderIcon"
    />
  )
}

export { CamelRouteFolderIcon }
