// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/camel-route.svg'

const CamelRouteIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CamelRouteIcon"
    />
  )
}

export { CamelRouteIcon }
