// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/camel-context-icon.svg'

const CamelContextIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CamelContextIcon"
    />
  )
}

export { CamelContextIcon }
