// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/channeladapter24.svg'

const ChanneladapterIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ChanneladapterIcon"
    />
  )
}

export { ChanneladapterIcon }
