// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/channelpurger24.svg'

const ChannelpurgerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ChannelpurgerIcon"
    />
  )
}

export { ChannelpurgerIcon }
