// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/choice24.svg'

const ChoiceIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ChoiceIcon"
    />
  )
}

export { ChoiceIcon }
