// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/commandmessage24.svg'

const CommandmessageIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CommandmessageIcon"
    />
  )
}

export { CommandmessageIcon }
