// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/competingconsumers24.svg'

const CompetingconsumersIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CompetingconsumersIcon"
    />
  )
}

export { CompetingconsumersIcon }
