// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/contentfilter24.svg'

const ContentfilterIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ContentfilterIcon"
    />
  )
}

export { ContentfilterIcon }
