// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/controlbus24.svg'

const ControlbusIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ControlbusIcon"
    />
  )
}

export { ControlbusIcon }
