// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/convertbodyto24.svg'

const ConvertbodytoIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ConvertbodytoIcon"
    />
  )
}

export { ConvertbodytoIcon }
