// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/correlationidentifier24.svg'

const CorrelationidentifierIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CorrelationidentifierIcon"
    />
  )
}

export { CorrelationidentifierIcon }
