// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/customdataformat24.svg'

const CustomdataformatIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CustomdataformatIcon"
    />
  )
}

export { CustomdataformatIcon }
