// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/datatypechannel24.svg'

const DatatypechannelIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="DatatypechannelIcon"
    />
  )
}

export { DatatypechannelIcon }
