// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/deadletterchannel24.svg'

const DeadletterchannelIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="DeadletterchannelIcon"
    />
  )
}

export { DeadletterchannelIcon }
