// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/distributionaggregate24.svg'

const DistributionaggregateIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="DistributionaggregateIcon"
    />
  )
}

export { DistributionaggregateIcon }
