// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/documentmessage24.svg'

const DocumentmessageIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="DocumentmessageIcon"
    />
  )
}

export { DocumentmessageIcon }
