// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/durablesubscription24.svg'

const DurablesubscriptionIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="DurablesubscriptionIcon"
    />
  )
}

export { DurablesubscriptionIcon }
