// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/dynamicrouter24.svg'

const DynamicrouterIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="DynamicrouterIcon"
    />
  )
}

export { DynamicrouterIcon }
