// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/edit-camel-route.svg'

const EditCamelRouteIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EditCamelRouteIcon"
    />
  )
}

export { EditCamelRouteIcon }
