// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/encapsulatedsynchronous24.svg'

const EncapsulatedsynchronousIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EncapsulatedsynchronousIcon"
    />
  )
}

export { EncapsulatedsynchronousIcon }
