// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/endpointFolder24.svg'

const EndpointFolderIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EndpointFolderIcon"
    />
  )
}

export { EndpointFolderIcon }
