// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/endpointdrools24.svg'

const EndpointdroolsIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EndpointdroolsIcon"
    />
  )
}

export { EndpointdroolsIcon }
