// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/endpointTimer24.svg'

const EndpointTimerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EndpointTimerIcon"
    />
  )
}

export { EndpointTimerIcon }
