// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/endpointRepository24.svg'

const EndpointRepositoryIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EndpointRepositoryIcon"
    />
  )
}

export { EndpointRepositoryIcon }
