// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/endpointQueue24.svg'

const EndpointQueueIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EndpointQueueIcon"
    />
  )
}

export { EndpointQueueIcon }
