// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/endpoint-node.svg'

const EndpointNodeIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EndpointNodeIcon"
    />
  )
}

export { EndpointNodeIcon }
