// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/enrich24.svg'

const EnrichIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EnrichIcon"
    />
  )
}

export { EnrichIcon }
