// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/envelopeWrapper24.svg'

const EnvelopeWrapperIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EnvelopeWrapperIcon"
    />
  )
}

export { EnvelopeWrapperIcon }
