// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/eventDrivenConsumer24.svg'

const EventDrivenConsumerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EventDrivenConsumerIcon"
    />
  )
}

export { EventDrivenConsumerIcon }
