// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/eventMessage24.svg'

const EventMessageIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EventMessageIcon"
    />
  )
}

export { EventMessageIcon }
