// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/fileTransfer24.svg'

const FileTransferIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="FileTransferIcon"
    />
  )
}

export { FileTransferIcon }
