// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/guaranteedMessaging24.svg'

const GuaranteedMessagingIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="GuaranteedMessagingIcon"
    />
  )
}

export { GuaranteedMessagingIcon }
