// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/idempotentConsumer24.svg'

const IdempotentConsumerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="IdempotentConsumerIcon"
    />
  )
}

export { IdempotentConsumerIcon }
