// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/invalidMessageChannel24.svg'

const InvalidMessageChannelIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="InvalidMessageChannelIcon"
    />
  )
}

export { InvalidMessageChannelIcon }
