// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/loadBalance24.svg'

const LoadBalanceIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="LoadBalanceIcon"
    />
  )
}

export { LoadBalanceIcon }
