// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messageBus24.svg'

const MessageBusIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessageBusIcon"
    />
  )
}

export { MessageBusIcon }
