// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messageDispatcher24.svg'

const MessageDispatcherIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessageDispatcherIcon"
    />
  )
}

export { MessageDispatcherIcon }
