// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messagingGateway24.svg'

const MessagingGatewayIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessagingGatewayIcon"
    />
  )
}

export { MessagingGatewayIcon }
