// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messageSequence24.svg'

const MessageSequenceIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessageSequenceIcon"
    />
  )
}

export { MessageSequenceIcon }
