// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messageBroker24.svg'

const MessageBrokerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessageBrokerIcon"
    />
  )
}

export { MessageBrokerIcon }
