// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messagingAdapter24.svg'

const MessagingAdapterIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessagingAdapterIcon"
    />
  )
}

export { MessagingAdapterIcon }
