// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messageSelector24.svg'

const MessageSelectorIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessageSelectorIcon"
    />
  )
}

export { MessageSelectorIcon }
