// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messageExpiration24.svg'

const MessageExpirationIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessageExpirationIcon"
    />
  )
}

export { MessageExpirationIcon }
