// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/messagingBridge24.svg'

const MessagingBridgeIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="MessagingBridgeIcon"
    />
  )
}

export { MessagingBridgeIcon }
