// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/normalizer24.svg'

const NormalizerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="NormalizerIcon"
    />
  )
}

export { NormalizerIcon }
