// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/pipeline24.svg'

const PipelineIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="PipelineIcon"
    />
  )
}

export { PipelineIcon }
