// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/pointToPoint24.svg'

const PointToPointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="PointToPointIcon"
    />
  )
}

export { PointToPointIcon }
