// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/pollEnrich24.svg'

const PollEnrichIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="PollEnrichIcon"
    />
  )
}

export { PollEnrichIcon }
