// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/pollingConsumer24.svg'

const PollingConsumerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="PollingConsumerIcon"
    />
  )
}

export { PollingConsumerIcon }
