// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/processManager24.svg'

const ProcessManagerIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ProcessManagerIcon"
    />
  )
}

export { ProcessManagerIcon }
