// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/processor24.svg'

const ProcessorIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ProcessorIcon"
    />
  )
}

export { ProcessorIcon }
