// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/recipientList24.svg'

const RecipientListIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="RecipientListIcon"
    />
  )
}

export { RecipientListIcon }
