// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/requestReply24.svg'

const RequestReplyIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="RequestReplyIcon"
    />
  )
}

export { RequestReplyIcon }
