// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/resequence24.svg'

const ResequenceIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ResequenceIcon"
    />
  )
}

export { ResequenceIcon }
