// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/returnAddress24.svg'

const ReturnAddressIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ReturnAddressIcon"
    />
  )
}

export { ReturnAddressIcon }
