// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/routingSlip24.svg'

const RoutingSlipIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="RoutingSlipIcon"
    />
  )
}

export { RoutingSlipIcon }
