// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/setBody24.svg'

const SetBodyIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SetBodyIcon"
    />
  )
}

export { SetBodyIcon }
