// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/sharedDatabase24.svg'

const SharedDatabaseIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SharedDatabaseIcon"
    />
  )
}

export { SharedDatabaseIcon }
