// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/smartProxy24.svg'

const SmartProxyIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SmartProxyIcon"
    />
  )
}

export { SmartProxyIcon }
