// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/storeInLibrary24.svg'

const StoreInLibraryIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="StoreInLibraryIcon"
    />
  )
}

export { StoreInLibraryIcon }
