// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/testMessage24.svg'

const TestMessageIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="TestMessageIcon"
    />
  )
}

export { TestMessageIcon }
