// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/transactionalClient24.svg'

const TransactionalClientIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="TransactionalClientIcon"
    />
  )
}

export { TransactionalClientIcon }
