// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/unmarshal24.svg'

const UnmarshalIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="UnmarshalIcon"
    />
  )
}

export { UnmarshalIcon }
