// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../svg/wireTap24.svg'

const WireTapIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="WireTapIcon"
    />
  )
}

export { WireTapIcon }
