// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/activemq24.svg'

const ActivemqEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ActivemqEndpointIcon"
    />
  )
}

export { ActivemqEndpointIcon }
