// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/cxfrs24.svg'

const CxfrsEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="CxfrsEndpointIcon"
    />
  )
}

export { CxfrsEndpointIcon }
