// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/ejb24.svg'

const EjbEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="EjbEndpointIcon"
    />
  )
}

export { EjbEndpointIcon }
