// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/facebook24.svg'

const FacebookEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="FacebookEndpointIcon"
    />
  )
}

export { FacebookEndpointIcon }
