// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/ftp24.svg'

const FtpEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="FtpEndpointIcon"
    />
  )
}

export { FtpEndpointIcon }
