// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/ftps24.svg'

const FtpsEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="FtpsEndpointIcon"
    />
  )
}

export { FtpsEndpointIcon }
