// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/imaps24.svg'

const ImapsEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="ImapsEndpointIcon"
    />
  )
}

export { ImapsEndpointIcon }
