// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/jdbc24.svg'

const JdbcEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="JdbcEndpointIcon"
    />
  )
}

export { JdbcEndpointIcon }
