// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/jms24.svg'

const JmsEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="JmsEndpointIcon"
    />
  )
}

export { JmsEndpointIcon }
