// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/language24.svg'

const LanguageEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="LanguageEndpointIcon"
    />
  )
}

export { LanguageEndpointIcon }
