// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/linkedin24.svg'

const LinkedinEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="LinkedinEndpointIcon"
    />
  )
}

export { LinkedinEndpointIcon }
