// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/netty4-http24.svg'

const Netty4HttpEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="Netty4HttpEndpointIcon"
    />
  )
}

export { Netty4HttpEndpointIcon }
