// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/netty424.svg'

const Netty4EndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="Netty4EndpointIcon"
    />
  )
}

export { Netty4EndpointIcon }
