// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/netty-http24.svg'

const NettyHttpEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="NettyHttpEndpointIcon"
    />
  )
}

export { NettyHttpEndpointIcon }
