// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/pop324.svg'

const Pop3EndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="Pop3EndpointIcon"
    />
  )
}

export { Pop3EndpointIcon }
