// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/pop3s24.svg'

const Pop3sEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="Pop3sEndpointIcon"
    />
  )
}

export { Pop3sEndpointIcon }
