// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/quartz24.svg'

const QuartzEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="QuartzEndpointIcon"
    />
  )
}

export { QuartzEndpointIcon }
