// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/quartz224.svg'

const Quartz2EndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="Quartz2EndpointIcon"
    />
  )
}

export { Quartz2EndpointIcon }
