// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/rss24.svg'

const RssEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="RssEndpointIcon"
    />
  )
}

export { RssEndpointIcon }
