// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/salesForce24.svg'

const SalesForceEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SalesForceEndpointIcon"
    />
  )
}

export { SalesForceEndpointIcon }
