// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/SAPNetweaver24.svg'

const SAPNetweaverEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SAPNetweaverEndpointIcon"
    />
  )
}

export { SAPNetweaverEndpointIcon }
