// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/sftp24.svg'

const SftpEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SftpEndpointIcon"
    />
  )
}

export { SftpEndpointIcon }
