// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/smtps24.svg'

const SmtpsEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SmtpsEndpointIcon"
    />
  )
}

export { SmtpsEndpointIcon }
