// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/smtp24.svg'

const SmtpEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SmtpEndpointIcon"
    />
  )
}

export { SmtpEndpointIcon }
