// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/snmp24.svg'

const SnmpEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="SnmpEndpointIcon"
    />
  )
}

export { SnmpEndpointIcon }
