// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/twitter24.svg'

const TwitterEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="TwitterEndpointIcon"
    />
  )
}

export { TwitterEndpointIcon }
