// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/weather24.svg'

const WeatherEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="WeatherEndpointIcon"
    />
  )
}

export { WeatherEndpointIcon }
