// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===
import svg from './../../svg/endpoints/xslt24.svg'

const XsltEndpointIcon = ({ size = 16 }) => {
  return (
    <img src={svg}
         width={size + 'px'} height={size + 'px'}
         alt="XsltEndpointIcon"
    />
  )
}

export { XsltEndpointIcon }
