#!/bin/bash

COMP="components"
END="endpoints"

genIconName() {
  local s="${1}"
  local suffix="${2}"

  fname=$(basename ${s} .svg)
  fname=$(basename ${fname} 24)
  fname=$(basename ${fname} '-icon')
  fname=$(basename ${fname} icon)
  fname="${fname^}"
  fname=$(echo ${fname} | awk -F"-" '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}} 1' OFS="")
  echo "${fname}${suffix}"
}

createComponent() {
  local dest="${1}"
  local svg="${2}"
  local icon="${3}"

  mkdir -p $(dirname ${dest})

  echo "// === THIS FILE WAS AUTO-GENERATED BY create-route-icon.sh ===" >> ${dest}
  echo "import svg from './${svg}'" >> ${dest}
  echo "" >> ${dest}
  echo "const ${icon} = ({ size = 16 }) => {" >> ${dest}
  echo "  return (" >> ${dest}
  echo "    <img src={svg}" >> ${dest}
  echo "         width={size + 'px'} height={size + 'px'}" >> ${dest}
  echo "         alt=\"${icon}\"" >> ${dest}
  echo "    />" >> ${dest}
  echo "  )" >> ${dest}
  echo "}" >> ${dest}
  echo "" >> ${dest}
  echo "export { ${icon} }" >> ${dest}
}

for s in svg/*.svg;
do
  echo "=== ${s} ==="

  fnameIcon=$(genIconName ${s} "Icon")
  fnameIconTsx="${fnameIcon}.tsx"

  if [ -f "${COMP}/${fnameIconTsx}" ]; then
    echo "Skipping ${fnameIconTsx}"
    continue
  fi

  createComponent "${COMP}/${fnameIconTsx}" "../${s}" "${fnameIcon}"
done

for s in svg/${END}/*.svg;
do
  echo "=== ${s} ==="

  fnameIcon="$(genIconName ${s} "EndpointIcon")"
  fnameIconTsx="${fnameIcon}.tsx"

  if [ -f "${COMP}/${END}/${fnameIconTsx}" ]; then
    echo "Skipping ${fnameIconTsx}"
    continue
  fi

  createComponent "${COMP}/${END}/${fnameIconTsx}" "../../${s}" "${fnameIcon}"
done
