name: Test

on:
  pull_request:
    branches:
      - main
      - 2.x
      - 1.9.x
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - 2.x
      - 1.9.x
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: ['20', '22']
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - name: Enable yarn v4
        run: |
          corepack enable
          yarn -v
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Audit
        run: yarn npm audit --all
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build:all
      - name: Test
        run: yarn test:all
